CREATE TABLE IF NOT EXISTS USERS (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  tipo ENUM('USER', 'ADMIN') NOT NULL,
  username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  FOREIGN KEY (role_id) REFERENCES ROLES(id)
);

CREATE TABLE IF NOT EXISTS MOVIES (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  ano_lancamento INT NOT NULL,
  duracao INT NOT NULL,
  classificacao_indicativa VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS REVIEWS (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  nota DOUBLE NOT NULL,
  nota_direcao DOUBLE NOT NULL,
  nota_fotografia DOUBLE NOT NULL,
  comentario TEXT,
  curtidas INT DEFAULT 0,
  denuncias INT DEFAULT 0,
  oculto BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (user_id) REFERENCES USERS(id),
  FOREIGN KEY (movie_id) REFERENCES MOVIES(id)
);

CREATE TABLE IF NOT EXISTS WATCHLISTS (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  assistido BOOLEAN DEFAULT FALSE,
  user_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS WATCHLIST_MOVIES (
  watchlist_id BIGINT NOT NULL,
  movie_id BIGINT NOT NULL,
  PRIMARY KEY (watchlist_id, movie_id),
  FOREIGN KEY (watchlist_id) REFERENCES WATCHLISTS(id),
  FOREIGN KEY (movie_id) REFERENCES MOVIES(id)
);

CREATE TABLE IF NOT EXISTS MOVIE_GENEROS (
  movie_id BIGINT NOT NULL,
  genero VARCHAR(100) NOT NULL,
  PRIMARY KEY (movie_id, genero),
  FOREIGN KEY (movie_id) REFERENCES MOVIES(id)
);
